### ISSUE TITLE
Add button to download pdf

### ISSUE THREAD

**Issue by thaispaiva** [CovidLP/app_COVID19#2]
- [x] Prepare markdown (ENG) and knit to generate html & pdf
- [x] Prepare markdown (POR) and knit to generate html & pdf
- [x] Add button to download
- [x] Create tab for POR & ENG

**Comment by DouglasMesquita** [comment]
Issue solved on commit [fbe0e5eed4cb41e388c2726c9eadd6c77a7b3da6](https://github.com/thaispaiva/app_COVID19/commit/fbe0e5eed4cb41e388c2726c9eadd6c77a7b3da6)
