### ISSUE TITLE
App is disconnecting when typing the country on LT tab

### ISSUE THREAD

**Issue by thaispaiva** [CovidLP/app_COVID19#7]
Check why the app disconnects when we try to type the name of a new country to display the results on the Long Term tab.

**Comment by DouglasMesquita** [comment]
Solved on commit [b514d10a13affafe3b9775f8107f7ec6e2e54288](https://github.com/thaispaiva/app_COVID19/commit/b514d10a13affafe3b9775f8107f7ec6e2e54288)
